// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

// 
//This source code was auto-generated by MonoXSD
//
namespace Uplift.Schemas {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Upfile {
        
        private string unityVersionField;
        
        private string packagesRootPathField;
        
        private Stub configurationField;
        
        private Repository[] repositoriesField;
        
        private DependencyDefinition[] dependenciesField;
        
        /// <remarks/>
        public string UnityVersion {
            get {
                return unityVersionField;
            }
            set {
                unityVersionField = value;
            }
        }
        
        /// <remarks/>
        public string PackagesRootPath {
            get {
                return packagesRootPathField;
            }
            set {
                packagesRootPathField = value;
            }
        }
        
        /// <remarks/>
        public Stub Configuration {
            get {
                return configurationField;
            }
            set {
                configurationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(typeof(FileRepository), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute(typeof(GitRepository), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute(typeof(WebRepository), IsNullable=false)]
        public Repository[] Repositories {
            get {
                return repositoriesField;
            }
            set {
                repositoriesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Package", IsNullable=false)]
        public DependencyDefinition[] Dependencies {
            get {
                return dependenciesField;
            }
            set {
                dependenciesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Stub {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InstallSpec {
        
        private string sourceField;
        
        private string destinationField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Source {
            get {
                return sourceField;
            }
            set {
                sourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Destination {
            get {
                return destinationField;
            }
            set {
                destinationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return valueField;
            }
            set {
                valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VersionSpec {
        
        private string itemField;
        
        private ItemChoiceType itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ExactVersion", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("MajorVersionMax", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("MajorVersionMin", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("MinVersion", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return itemField;
            }
            set {
                itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return itemElementNameField;
            }
            set {
                itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <remarks/>
        ExactVersion,
        
        /// <remarks/>
        MajorVersionMax,
        
        /// <remarks/>
        MajorVersionMin,
        
        /// <remarks/>
        MinVersion,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DependencyDefinition {
        
        private VersionSpec itemField;
        
        private string nameField;
        
        private string versionField;
        
        private string repositoryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Version")]
        public VersionSpec Item {
            get {
                return itemField;
            }
            set {
                itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return nameField;
            }
            set {
                nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Version {
            get {
                return versionField;
            }
            set {
                versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Repository {
            get {
                return repositoryField;
            }
            set {
                repositoryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FileRepository))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GitRepository))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WebRepository))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Repository {
        
        private string extractPathField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ExtractPath {
            get {
                return extractPathField;
            }
            set {
                extractPathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return valueField;
            }
            set {
                valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FileRepository : Repository {
        
        private string pathField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Path {
            get {
                return pathField;
            }
            set {
                pathField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GitRepository : Repository {
        
        private string urlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Url {
            get {
                return urlField;
            }
            set {
                urlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WebRepository : Repository {
        
        private string urlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Url {
            get {
                return urlField;
            }
            set {
                urlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Upset {
        
        private VersionSpec unityVersionField;
        
        private string packageNameField;
        
        private string packageVersionField;
        
        private string packageLicenseField;
        
        private DependencyDefinition[] dependenciesField;
        
        private InstallSpec[] installSpecificationsField;
        
        /// <remarks/>
        public VersionSpec UnityVersion {
            get {
                return unityVersionField;
            }
            set {
                unityVersionField = value;
            }
        }
        
        /// <remarks/>
        public string PackageName {
            get {
                return packageNameField;
            }
            set {
                packageNameField = value;
            }
        }
        
        /// <remarks/>
        public string PackageVersion {
            get {
                return packageVersionField;
            }
            set {
                packageVersionField = value;
            }
        }
        
        /// <remarks/>
        public string PackageLicense {
            get {
                return packageLicenseField;
            }
            set {
                packageLicenseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Package", IsNullable=false)]
        public DependencyDefinition[] Dependencies {
            get {
                return dependenciesField;
            }
            set {
                dependenciesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Spec", IsNullable=false)]
        public InstallSpec[] InstallSpecifications {
            get {
                return installSpecificationsField;
            }
            set {
                installSpecificationsField = value;
            }
        }
    }
}
