# This Rakefile is primarily used by the developers for automation purposes
#
# Please refrain from expanding this file unless really necessary

task :chdir do
    file = File.symlink?(__FILE__) ? File.readlink(__FILE__) : __FILE__
    rakefile_dir = File.expand_path File.dirname file
    Dir.chdir(File.join(rakefile_dir, '..'))
end

task :install_gems => [:chdir] do
    sh('bundle install')
end

desc "Run the tests using u3d"
task :test => [:chdir] do
    pwd = Dir.pwd
    sh "bundle exec u3d run -- -logFile u3d.log -runTests -projectPath #{pwd} -testResults #{pwd}/results.xml -testPlatform editmode -batchmode"
end

task :build_5_0 do
    sh 'rm -rf ./Assets/Plugins/Editor/Uplift/Testing* Assets/Plugins/Editor/Uplift/Properties/TestingProperties.cs*'
    sh 'echo "m_EditorVersion: 5.0.4f1" > ProjectSettings/ProjectVersion.txt'
    sh 'echo "m_EditorVersion: 5.0.4f1" > Build/ProjectSettings/ProjectVersion.txt'
    Rake::Task["build"].execute
end

desc 'Build the Uplift DLL and the unitypackage contain the DLL and its dependencies'
task :build => [:chdir] do
    sh('bundle exec u3d -- -logFile u3d.log -batchmode -quit -executeMethod BuildTool.DllCompiler.BuildPackage')

    editor_dir = File.join('Assets', 'Plugins', 'Editor')
    # prepare a Unity package
    dirs = [ editor_dir ]
    uplift_package = File.absolute_path File.join('target', 'Uplift.unitypackage')
    Dir.chdir('Build') do
        sh("bundle exec u3d -- -logFile u3d.log -batchmode -quit -exportPackage #{dirs.join(" ")} #{uplift_package}")
    end
    puts "File #{uplift_package} generated!"
end
